#lang pollen

◊h1{Systems thinking}

◊leading-words{Everything} is related to everything else. You cannot really understand things in isolation but need to take the environment, the context, into account. You can't understand what a car is just by taking it into pieces. To get the whole picture, you also need to know who is using it, for what and how exactly. Cars are not just wheels and engines. They are streets, parking lots, taxi drivers, speeding tickets and road trips too.

You want to cook a dinner. The ingredients that go into the food are called inputs. These ingredients have different functions. Some provide flavor, some bring color, some are there just to fill your stomach. The steps you make to make the food is called process. The purpose of the stove or oven you use is to heat the food and the result you serve on the table is the output. If you look and taste the food, you can get some feedback about the quality, and you can use that knowledge to tune the parameters, the ingredients or the cooking time, to get better results next time. You get the context from the facts, that it is Winter in Alaska and it's your new date whom you are making dinner for the very first time. The expression on your date's face gives you feedback again. Maybe your main course was a delicious steak. You just didn't take into account the fact that your date is vegetarian. Oops.

Systems thinking is a way to solve all kinds of problems by seeing them as a part of a bigger whole. No matter how good your steak is, no matter how optimized your cooking process is, you can still fail if you don't take the context into account. Systems give us a language and terms to talk and think about any activity, regardless of the scale or the subject. You can use that terminology to discuss both cooking and global economics. 
